services:
  api_rewards:
    # platform: linux/arm64/v8
    build:
      context: ./backend_app
      dockerfile: Dockerfile
    container_name: api_rewards
    restart: unless-stopped
    volumes:
      - ./backend_app:/app
      - ./backend_app/gunicorn.conf.py:/etc/nginx/gunicorn.conf.py
      - ./backend_app/static:/app/staticfiles
    ports:
      - "8002:8000"
    env_file:
      - ./backend_app/.env
    networks:
      - shared-network

  mongodb_installation:
    # platform: linux/arm64/v8
    image: mongo:7.0
    container_name: mongodb_installation
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - ./mongo_db/.env
    volumes:
      - mongodb_data:/data/db
      - ./mongo_db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - shared-network

volumes:
  mongodb_data:

networks:
  shared-network:
    external: true
    driver: bridge