"""
Django settings for system_reward_points project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from celery.schedules import crontab
from datetime import timedelta
from .mongo_setup import (
    connect_mongo
)
import os
import environ
import warnings 
import urllib.parse


env = environ.Env(
    DEBUG=(bool, False)
)

environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

REDIS_HOST = env('REDIS_HOST', default='localhost')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'detailed': {
            'format': (
                '%(asctime)s %(levelname)-8s '
                '[%(filename)s:%(lineno)d %(funcName)s()] '
                '%(message)s'
            ),
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/var/log/celery.log',
            'formatter': 'detailed',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'detailed',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'celery': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'root': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    },
}

# DANGO VARS
DJANGO_REGISTER_USER_ROLE = env('DJANGO_REGISTER_USER_ROLE', default='client')
DJANGO_LIST_ADMIN_EMAIL_RECEIPTS = env.list('DJANGO_LIST_ADMIN_EMAIL_RECEIPTS', default=[])

# SSO
SSO_SHARED_SECRET = env('SSO_SHARED_SECRET', default='')
SSO_ISSUER = env('SSO_ISSUER', default='NWSIntegrationSystems')
SSO_AUDIENCE_CUSTOMERPORTAL = env('SSO_AUDIENCE_CUSTOMERPORTAL', default='CustomerPortalSystem')

# FRONTEND_URL
FRONTEND_URL = env('FRONTEND_URL', default='https://customerportal.newwindowsystem.net')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--i$a=heuuy55t_!15ketws1@ks01x4zc3b@0paekw7&g$7r8k7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

CSRF_COOKIE_SECURE = False  

CSRF_COOKIE_NAME = 'csrftoken'

CSRF_COOKIE_HTTPONLY = False

CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'

CSRF_COOKIE_SAMESITE = None

SESSION_COOKIE_SECURE = True

SESSION_COOKIE_SAMESITE = None

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

CORS_ALLOW_HEADERS = [
    'Authorization',
    'Content-Type',
    'Accept',
    'x-requested-with',
    'accept',
    'origin',
    'user-agent',
    'dnt',
    'cache-control',
    'X-CSRFToken',
    'x-requested-with',
    'x-xsrf-token',
]

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'graphene_django',
    'api_integration',
    'api_authorization',
    # 'api_projects',
    'api_reward_points.apps.ApiRewardPointsConfig',
    'api_users.apps.ApiUsersConfig',
    'api_reward_points_async_task_sequence',
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api_authorization.middleware.MongoAuthMiddleware',
    'api_authorization.middleware.MongoConnectionMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'api_authorization.backends.MongoDBBackend',
]

SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'


ROOT_URLCONF = 'system_reward_points.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(REDIS_HOST, 6379, 3)], 
        },
        'CAPACITY': 1500,
    },
}

WSGI_APPLICATION = 'system_reward_points.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

BASE_DIR_STATIC = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


BACKUP_DIR = os.path.join(BASE_DIR, 'backup')

MEDIA_URL = '/backup/'
MEDIA_ROOT = BACKUP_DIR

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST FRAMEWORK
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=59),  # 1 hour
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ACCESS_TOKEN_LIFETIME_REMEMBER': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME_REMEMBER': timedelta(days=60),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'USER_ID_FIELD': 'id',  
    'USER_ID_CLAIM': 'user_id',
}

# EMAIL SETTINGS
EMAIL_BACKEND = env("EMAIL_BACKEND", default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST_USER = env("EMAIL_HOST_USER") 
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_USE_TLS = env('EMAIL_USE_TLS')
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')

# AWS
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', default='')
AWS_REGION = env('AWS_REGION', default='')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME', default='')
AWS_S3_FOLDER_STORE_PRODUCTS = env('AWS_S3_FOLDER_STORE_PRODUCTS', default='store_products/')
AWS_S3_FOLDER_STORE_AVATARS = env('AWS_S3_FOLDER_STORE_AVATARS', default='avatars/')
AWS_S3_FOLDER_BACKUPS = env('AWS_S3_FOLDER_BACKUPS', default='backups/mongodb/')

# API MAIN DATA
API_MAIN_DATA_URL = env('API_MAIN_DATA_URL', default='')
API_USER_DATA_URL = env('API_USER_DATA_URL', default='')
API_MAIN_DATA_TOKEN = env('API_MAIN_DATA_TOKEN', default='')


# Celery
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='')
CELERY_TASKS_DELAY = env('CELERY_TASKS_DELAY', default=5)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/New_York'
CELERY_ENABLE_UTC = False

# Celery Beat Schedule
CELERY_TASK_REVIEW_USER_POINTS_MIN = env('CELERY_TASK_REVIEW_USER_POINTS_MIN', default='*/30')  # Every 5 minute
CELERY_TASK_REVIEW_USER_POINTS_HOUR = env('CELERY_TASK_REVIEW_USER_POINTS_HOUR', default='7-17')
CELERY_TASK_REVIEW_USER_POINTS_DAY_OF_WEEK = env('CELERY_TASK_REVIEW_USER_POINTS_DAY_OF_WEEK', default='*')

CELERY_BEAT_SCHEDULE = {
    'run-task-sequence-every-5-min': {
        'task': 'api_reward_points_async_task_sequence.tasks.task_sequence_every_10_min',
        'schedule': crontab(
            minute=CELERY_TASK_REVIEW_USER_POINTS_MIN, 
            hour=CELERY_TASK_REVIEW_USER_POINTS_HOUR, 
            day_of_week=CELERY_TASK_REVIEW_USER_POINTS_DAY_OF_WEEK
        ),
    },
    'run-task-sequence-daily': {
        'task': 'api_reward_points_async_task_sequence.tasks.task_sequence_daily',
        'schedule': crontab(minute=0, hour=8, day_of_week='*'),
        # 'schedule': crontab(minute='*/2', hour='7-17', day_of_week='*'),
    },
}


# ZOHO
ZOHO_ORG_ID = env('ZOHO_ORG_ID', default='')
ZOHO_ORG_NWS_ID = env('ZOHO_ORG_NWS_ID', default='')

# MONGOENGINE

warnings.filterwarnings("ignore", message="MongoClient opened before fork")

MONGO_HOST = env('MONGO_HOST', default='localhost')
MONGO_PORT = int(env('MONGO_PORT', default=27017))
MONGO_USER = env('MONGO_USER', default='root')
MONGO_PASSWORD = env('MONGO_PASSWORD', default='')
MONGO_DB = env('MONGO_DB', default='')
MONGO_URI = f"mongodb://{MONGO_USER}:{urllib.parse.quote_plus(MONGO_PASSWORD)}@{MONGO_HOST}:{MONGO_PORT}/{MONGO_DB}?authSource=admin&authMechanism=SCRAM-SHA-1"

connect_mongo()